######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 6 10:50:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mxd.h netsetup.h
SOURCES += main.cpp mxd.cpp netsetup.cpp
TRANSLATIONS += mxd_cn.ts
